spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
springdoc:
  enable-kotlin: true
  packages-to-scan: com.example.stamp.controllers
---
spring:
  config:
    activate:
      on-profile: development
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    hikari:
      username: user
      password: admin
    url: jdbc:h2:file:~/test
---
spring:
  config:
    activate:
      on-profile: staging, production
  datasource:
    hikari:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    url: ${DB_JDBC_URL}