spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    hikari:
      username: user
      password: admin
    url: jdbc:h2:file:~/test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db/changelog/db.changelog-master.xml
springdoc:
  enable-kotlin: true
  packages-to-scan: com.example.stamp.controllers
server:
  port: 8881